Repository semantic-release/release-notes-generator, pull requests merged in 2019-11, with the labels that each got.

#149 docs: fix typo in `preset` list
  README.md
Labels: docs, plugin:release-notes

#150 docs(readme): fix typos in usage section
  README.md
Labels: docs, plugin:release-notes

#152 fix: ignore custom port when converting ssh repo URL to https
  index.js
  test/integration.test.js
Labels: plugin:release-notes

#157 fix: filter out commits with empty message
  index.js
  test/integration.test.js
Labels: bug, plugin:release-notes
